### ISSUE TITLE
Skip custom handling for old image identifiers when using multiple hosts

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imboclient-php#115]
Imbo used to generate [MD5](https://en.wikipedia.org/wiki/MD5) hashes as image identifiers. If the client is configured using multiple Imbo hosts it will deterministically choose a host based on the image identifier. Version 2 of the client includes custom logic to "correctly" choose the host when the image identifier looks like an MD5 hash. This custom logic should be removed in version 3.

**Comment by christeredvartsen** [comment]
This was fixed somewhere in the implementation of version 3, unable to pinpoint the exact commit as the client was basically written from scratch.

**Comment by matslindh** [comment]
This change reduces the maximum number of servers that gets request with the old formats to 16 - _if_ you do load balancing in the client and not on your regular load balancer. I don't see anyone being affected by this.

If you need to load balance across more than 16 servers _in the client_ and have the old md5 identifiers, create two lists of servers and pick one on random. It will give you a larger transformation cache (2x), but you'll effectively get the same load balancing scheme as previously. Make sure these lists are stable and not random - since the selection otherwise would be redudant.
